### ISSUE TITLE
Incluir atributos de inicio y fin de asistencia

### ISSUE THREAD

**Issue by virtor** [CiudadesAbiertas/vocab-sector-publico-agenda-municipal#3]
Los responsables de las agendas de cada persona, rellenan el tiempo que la persona va a estar en un acto, es decir, puede ser que para el mismo acto las personas asistan en diferentes momentos, por lo que al existir una única fecha asociada al evento no podríamos representar el tiempo que una persona tiene pensado asistir al mismo.

Nuestra propuesta sería añadir en la tabla rol_integrante_evento los atributos opcionales de inicio y fin de asistencia.

**Comment by ednaru** [comment]
Se agregarán nuevos data properties que serán incorporados al siguiente release del vocabulario, tanto a la ontología y su documentación como a las tablas correspondientes

**Comment by ednaru** [comment]
Se representa el inicio y el final de aistencia de una persona como propiedades inicioAsistencia y finAsistencia con dominio RolIntegranteEvento (representa cada participante en un evento).
