### ISSUE TITLE
Nombre y apellidos del agente (persona física) en atributos separados

### ISSUE THREAD

**Issue by gallegosanmj** [CiudadesAbiertas/vocab-sector-publico-agenda-municipal#4]
Nuestra propuesta es que si el agente es persona física se tiene que abordar por separado el nombre, apellido1 y apellido 2.

**Comment by ednaru** [comment]
Se agregarán nuevos data properties para separar nombre y apellido en la clase foaf:Person que representa a la persona física. (subclase de foaf:Agent)

**Comment by gallegosanmj** [comment]
De acuerdo con la propuesta. Debe contemplarse la separación de los 3: nombre, primer apellido y segundo apellido.

**Comment by ocorcho** [comment]
Lo más conveniente será tener esta separación en tres (nombre, primer apellido y segundo apellido) y también recomendar como atributo opcional el nombre completo, para así permitir tanto a los que tienen que gestionar los datos (opción de separación en tres) como a los reutilizadores que no estén tan interesados en esa división (opción de un único atributo) representar la información. Esto es habitual en muchos sistemas.

**Comment by ednaru** [comment]
Se representan el nombre, primer apellido y segundo apellido mediante una clase Persona que es subclase de foaf:Person con las propiedades nombre, apellido1 y apellido2.
