### ISSUE TITLE
Direcciones normalizadas para ubicaciones de eventos

### ISSUE THREAD

**Issue by gallegosanmj** [CiudadesAbiertas/vocab-sector-publico-agenda-municipal#5]
Nuestra propuesta es que para cualquier ubicación de un evento hay que especificar la dirección normalizada (tipo de vial, nombre de vial, partícula, clase de numeración y numero)

**Comment by ednaru** [comment]
El lugar de un evento tiene como subclase a Equipamiento del vocabulario de equipamiento municipal, esta clase a su vez se relacionaría con la clase Dirección Postal del vocabulario de direcciones postales que ya la tiene normalizada. @gallegosanmj se requiere saber si para los casos en que el lugar de un evento NO sea un equipamiento también requieren que la dirección normalizada.

**Comment by gallegosanmj** [comment]
En los casos en los que el lugar de un evento NO es un equipamiento también se requiere la dirección normalizada .

**Comment by ocorcho** [comment]
De acuerdo, entonces mantendremos una dirección normalizada sobre todo en vistas a su utilización interna, así como una dirección no normalizada siguiendo las prácticas habituales de  schema:PostalAddress, para permitir los dos tipos de reutilización. Esto debe tenerse en cuenta en el vocabulario de DirecciónPostal

**Comment by ocorcho** [comment]
En el repositorio relacionado con direcciones postales (https://github.com/opencitydata/commons-direccion-postal/) y en el de callejero (https://github.com/opencitydata/urbanismo-infraestructuras-callejero) se han incluido los atributos necesarios para representar este tipo de direcciones normalizadas, siguiendo las indicaciones propuestas por los grupos de trabajo de INSPIRE.

**Comment by ocorcho** [comment]
@ednaru añadirá ejemplos en la documentación del vocabulario

**Comment by ednaru** [comment]
La dirección no normalizada se representa mediante la propiedad fullAddress.
